// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxpvkaxgypmnwjmcgnlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cHZrYXhneXBtbndqbWNnbmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTIyODMsImV4cCI6MjA1MzM2ODI4M30.RF8fV7a0xVnR-rDMkSObk6f7OFW9fnMT-Lu4EDfOSt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);